/*
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.xmodel


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XModelStandaloneSetup extends XModelStandaloneSetupGenerated {

	def static void doSetup() {
		new XModelStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
