/*
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.xmodel


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class XModelRuntimeModule extends AbstractXModelRuntimeModule {
}
