/*
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.xmodel.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class XModelProposalProvider extends AbstractXModelProposalProvider {
}
