/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.xmodel;

import org.xtext.example.xmodel.AbstractXModelRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class XModelRuntimeModule extends AbstractXModelRuntimeModule {
}
