/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.xmodel;

import org.xtext.example.xmodel.XModelStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class XModelStandaloneSetup extends XModelStandaloneSetupGenerated {
  public static void doSetup() {
    new XModelStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
