/*
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.xmodel.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.xmodel.ui.internal.XmodelActivator;

public class XModelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XmodelActivator.getInstance().getInjector("org.xtext.example.xmodel.XModel");
	}

}
