/*
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.xmodel.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.xmodel.ui.internal.XmodelActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XModelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(XmodelActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		XmodelActivator activator = XmodelActivator.getInstance();
		return activator != null ? activator.getInjector(XmodelActivator.ORG_XTEXT_EXAMPLE_XMODEL_XMODEL) : null;
	}

}
