/*
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.xmodel.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.xmodel.parser.antlr.internal.InternalXModelParser;
import org.xtext.example.xmodel.services.XModelGrammarAccess;

public class XModelParser extends AbstractAntlrParser {

	@Inject
	private XModelGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalXModelParser createParser(XtextTokenStream stream) {
		return new InternalXModelParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Package";
	}

	public XModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
