/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.xmodel.ui.contentassist;

import org.xtext.example.xmodel.ui.contentassist.AbstractXModelProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class XModelProposalProvider extends AbstractXModelProposalProvider {
}
