/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.xmodel.ide;

import org.xtext.example.xmodel.ide.AbstractXModelIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class XModelIdeModule extends AbstractXModelIdeModule {
}
