/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.xmodel.xModel.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.xtext.example.xmodel.xModel.XClass;
import org.xtext.example.xmodel.xModel.XModelFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>XClass</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class XClassTest extends TestCase {

	/**
	 * The fixture for this XClass test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected XClass fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(XClassTest.class);
	}

	/**
	 * Constructs a new XClass test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public XClassTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this XClass test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(XClass fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this XClass test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected XClass getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(XModelFactory.eINSTANCE.createXClass());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //XClassTest
