/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.xmodel.xModel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.xmodel.xModel.Operation#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.xmodel.xModel.Operation#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.example.xmodel.xModel.Operation#getVisibility <em>Visibility</em>}</li>
 *   <li>{@link org.xtext.example.xmodel.xModel.Operation#getXtype <em>Xtype</em>}</li>
 *   <li>{@link org.xtext.example.xmodel.xModel.Operation#getParameter <em>Parameter</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.xmodel.xModel.XModelPackage#getOperation()
 * @model
 * @generated
 */
public interface Operation extends EObject
{
  /**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see org.xtext.example.xmodel.xModel.XModelPackage#getOperation_Name()
	 * @model
	 * @generated
	 */
  String getName();

  /**
	 * Sets the value of the '{@link org.xtext.example.xmodel.xModel.Operation#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
  void setName(String value);

  /**
	 * Returns the value of the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Description</em>' attribute.
	 * @see #setDescription(String)
	 * @see org.xtext.example.xmodel.xModel.XModelPackage#getOperation_Description()
	 * @model
	 * @generated
	 */
  String getDescription();

  /**
	 * Sets the value of the '{@link org.xtext.example.xmodel.xModel.Operation#getDescription <em>Description</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Description</em>' attribute.
	 * @see #getDescription()
	 * @generated
	 */
  void setDescription(String value);

  /**
	 * Returns the value of the '<em><b>Visibility</b></em>' attribute.
	 * The literals are from the enumeration {@link org.xtext.example.xmodel.xModel.Visibility}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Visibility</em>' attribute.
	 * @see org.xtext.example.xmodel.xModel.Visibility
	 * @see #setVisibility(Visibility)
	 * @see org.xtext.example.xmodel.xModel.XModelPackage#getOperation_Visibility()
	 * @model
	 * @generated
	 */
  Visibility getVisibility();

  /**
	 * Sets the value of the '{@link org.xtext.example.xmodel.xModel.Operation#getVisibility <em>Visibility</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Visibility</em>' attribute.
	 * @see org.xtext.example.xmodel.xModel.Visibility
	 * @see #getVisibility()
	 * @generated
	 */
  void setVisibility(Visibility value);

  /**
	 * Returns the value of the '<em><b>Xtype</b></em>' attribute.
	 * The literals are from the enumeration {@link org.xtext.example.xmodel.xModel.XType}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Xtype</em>' attribute.
	 * @see org.xtext.example.xmodel.xModel.XType
	 * @see #setXtype(XType)
	 * @see org.xtext.example.xmodel.xModel.XModelPackage#getOperation_Xtype()
	 * @model
	 * @generated
	 */
  XType getXtype();

  /**
	 * Sets the value of the '{@link org.xtext.example.xmodel.xModel.Operation#getXtype <em>Xtype</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Xtype</em>' attribute.
	 * @see org.xtext.example.xmodel.xModel.XType
	 * @see #getXtype()
	 * @generated
	 */
  void setXtype(XType value);

  /**
	 * Returns the value of the '<em><b>Parameter</b></em>' containment reference list.
	 * The list contents are of type {@link org.xtext.example.xmodel.xModel.Parameter}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Parameter</em>' containment reference list.
	 * @see org.xtext.example.xmodel.xModel.XModelPackage#getOperation_Parameter()
	 * @model containment="true"
	 * @generated
	 */
  EList<Parameter> getParameter();

} // Operation
