/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.xmodel.xModel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Package</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.xmodel.xModel.Package#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.xmodel.xModel.Package#getClass_ <em>Class</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.xmodel.xModel.XModelPackage#getPackage()
 * @model
 * @generated
 */
public interface Package extends EObject
{
  /**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * The default value is <code>"pac"</code>.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see org.xtext.example.xmodel.xModel.XModelPackage#getPackage_Name()
	 * @model default="pac"
	 * @generated
	 */
  String getName();

  /**
	 * Sets the value of the '{@link org.xtext.example.xmodel.xModel.Package#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
  void setName(String value);

  /**
	 * Returns the value of the '<em><b>Class</b></em>' containment reference list.
	 * The list contents are of type {@link org.xtext.example.xmodel.xModel.XClass}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Class</em>' containment reference list.
	 * @see org.xtext.example.xmodel.xModel.XModelPackage#getPackage_Class()
	 * @model containment="true"
	 * @generated
	 */
  EList<XClass> getClass_();

} // Package
