/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.xmodel.xModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.xmodel.xModel.Parameter#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.xmodel.xModel.Parameter#getXtype <em>Xtype</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.xmodel.xModel.XModelPackage#getParameter()
 * @model
 * @generated
 */
public interface Parameter extends EObject
{
  /**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see org.xtext.example.xmodel.xModel.XModelPackage#getParameter_Name()
	 * @model
	 * @generated
	 */
  String getName();

  /**
	 * Sets the value of the '{@link org.xtext.example.xmodel.xModel.Parameter#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
  void setName(String value);

  /**
	 * Returns the value of the '<em><b>Xtype</b></em>' attribute.
	 * The literals are from the enumeration {@link org.xtext.example.xmodel.xModel.XType}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Xtype</em>' attribute.
	 * @see org.xtext.example.xmodel.xModel.XType
	 * @see #setXtype(XType)
	 * @see org.xtext.example.xmodel.xModel.XModelPackage#getParameter_Xtype()
	 * @model
	 * @generated
	 */
  XType getXtype();

  /**
	 * Sets the value of the '{@link org.xtext.example.xmodel.xModel.Parameter#getXtype <em>Xtype</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Xtype</em>' attribute.
	 * @see org.xtext.example.xmodel.xModel.XType
	 * @see #getXtype()
	 * @generated
	 */
  void setXtype(XType value);

} // Parameter
