/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.xmodel.xModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.xmodel.xModel.Property#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.xmodel.xModel.Property#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.example.xmodel.xModel.Property#getVisibility <em>Visibility</em>}</li>
 *   <li>{@link org.xtext.example.xmodel.xModel.Property#getXtype <em>Xtype</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.xmodel.xModel.XModelPackage#getProperty()
 * @model
 * @generated
 */
public interface Property extends EObject
{
  /**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see org.xtext.example.xmodel.xModel.XModelPackage#getProperty_Name()
	 * @model
	 * @generated
	 */
  String getName();

  /**
	 * Sets the value of the '{@link org.xtext.example.xmodel.xModel.Property#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
  void setName(String value);

  /**
	 * Returns the value of the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Description</em>' attribute.
	 * @see #setDescription(String)
	 * @see org.xtext.example.xmodel.xModel.XModelPackage#getProperty_Description()
	 * @model
	 * @generated
	 */
  String getDescription();

  /**
	 * Sets the value of the '{@link org.xtext.example.xmodel.xModel.Property#getDescription <em>Description</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Description</em>' attribute.
	 * @see #getDescription()
	 * @generated
	 */
  void setDescription(String value);

  /**
	 * Returns the value of the '<em><b>Visibility</b></em>' attribute.
	 * The literals are from the enumeration {@link org.xtext.example.xmodel.xModel.Visibility}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Visibility</em>' attribute.
	 * @see org.xtext.example.xmodel.xModel.Visibility
	 * @see #setVisibility(Visibility)
	 * @see org.xtext.example.xmodel.xModel.XModelPackage#getProperty_Visibility()
	 * @model
	 * @generated
	 */
  Visibility getVisibility();

  /**
	 * Sets the value of the '{@link org.xtext.example.xmodel.xModel.Property#getVisibility <em>Visibility</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Visibility</em>' attribute.
	 * @see org.xtext.example.xmodel.xModel.Visibility
	 * @see #getVisibility()
	 * @generated
	 */
  void setVisibility(Visibility value);

  /**
	 * Returns the value of the '<em><b>Xtype</b></em>' attribute.
	 * The literals are from the enumeration {@link org.xtext.example.xmodel.xModel.XType}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Xtype</em>' attribute.
	 * @see org.xtext.example.xmodel.xModel.XType
	 * @see #setXtype(XType)
	 * @see org.xtext.example.xmodel.xModel.XModelPackage#getProperty_Xtype()
	 * @model
	 * @generated
	 */
  XType getXtype();

  /**
	 * Sets the value of the '{@link org.xtext.example.xmodel.xModel.Property#getXtype <em>Xtype</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Xtype</em>' attribute.
	 * @see org.xtext.example.xmodel.xModel.XType
	 * @see #getXtype()
	 * @generated
	 */
  void setXtype(XType value);

} // Property
