/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.xmodel.xModel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XClass</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.xmodel.xModel.XClass#isIsAbstract <em>Is Abstract</em>}</li>
 *   <li>{@link org.xtext.example.xmodel.xModel.XClass#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.xmodel.xModel.XClass#getDescription <em>Description</em>}</li>
 *   <li>{@link org.xtext.example.xmodel.xModel.XClass#getExtend <em>Extend</em>}</li>
 *   <li>{@link org.xtext.example.xmodel.xModel.XClass#getProperty <em>Property</em>}</li>
 *   <li>{@link org.xtext.example.xmodel.xModel.XClass#getOperation <em>Operation</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.xmodel.xModel.XModelPackage#getXClass()
 * @model
 * @generated
 */
public interface XClass extends EObject
{
  /**
	 * Returns the value of the '<em><b>Is Abstract</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Is Abstract</em>' attribute.
	 * @see #setIsAbstract(boolean)
	 * @see org.xtext.example.xmodel.xModel.XModelPackage#getXClass_IsAbstract()
	 * @model
	 * @generated
	 */
  boolean isIsAbstract();

  /**
	 * Sets the value of the '{@link org.xtext.example.xmodel.xModel.XClass#isIsAbstract <em>Is Abstract</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Is Abstract</em>' attribute.
	 * @see #isIsAbstract()
	 * @generated
	 */
  void setIsAbstract(boolean value);

  /**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see org.xtext.example.xmodel.xModel.XModelPackage#getXClass_Name()
	 * @model
	 * @generated
	 */
  String getName();

  /**
	 * Sets the value of the '{@link org.xtext.example.xmodel.xModel.XClass#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
  void setName(String value);

  /**
	 * Returns the value of the '<em><b>Description</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Description</em>' attribute.
	 * @see #setDescription(String)
	 * @see org.xtext.example.xmodel.xModel.XModelPackage#getXClass_Description()
	 * @model
	 * @generated
	 */
  String getDescription();

  /**
	 * Sets the value of the '{@link org.xtext.example.xmodel.xModel.XClass#getDescription <em>Description</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Description</em>' attribute.
	 * @see #getDescription()
	 * @generated
	 */
  void setDescription(String value);

  /**
	 * Returns the value of the '<em><b>Extend</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Extend</em>' attribute.
	 * @see #setExtend(String)
	 * @see org.xtext.example.xmodel.xModel.XModelPackage#getXClass_Extend()
	 * @model
	 * @generated
	 */
  String getExtend();

  /**
	 * Sets the value of the '{@link org.xtext.example.xmodel.xModel.XClass#getExtend <em>Extend</em>}' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Extend</em>' attribute.
	 * @see #getExtend()
	 * @generated
	 */
  void setExtend(String value);

  /**
	 * Returns the value of the '<em><b>Property</b></em>' containment reference list.
	 * The list contents are of type {@link org.xtext.example.xmodel.xModel.Property}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Property</em>' containment reference list.
	 * @see org.xtext.example.xmodel.xModel.XModelPackage#getXClass_Property()
	 * @model containment="true"
	 * @generated
	 */
  EList<Property> getProperty();

  /**
	 * Returns the value of the '<em><b>Operation</b></em>' containment reference list.
	 * The list contents are of type {@link org.xtext.example.xmodel.xModel.Operation}.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Operation</em>' containment reference list.
	 * @see org.xtext.example.xmodel.xModel.XModelPackage#getXClass_Operation()
	 * @model containment="true"
	 * @generated
	 */
  EList<Operation> getOperation();

} // XClass
