/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.xmodel.xModel;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.xmodel.xModel.XModelPackage
 * @generated
 */
public interface XModelFactory extends EFactory
{
  /**
	 * The singleton instance of the factory.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  XModelFactory eINSTANCE = org.xtext.example.xmodel.xModel.impl.XModelFactoryImpl.init();

  /**
	 * Returns a new object of class '<em>Package</em>'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return a new object of class '<em>Package</em>'.
	 * @generated
	 */
  Package createPackage();

  /**
	 * Returns a new object of class '<em>XClass</em>'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return a new object of class '<em>XClass</em>'.
	 * @generated
	 */
  XClass createXClass();

  /**
	 * Returns a new object of class '<em>Property</em>'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return a new object of class '<em>Property</em>'.
	 * @generated
	 */
  Property createProperty();

  /**
	 * Returns a new object of class '<em>Operation</em>'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return a new object of class '<em>Operation</em>'.
	 * @generated
	 */
  Operation createOperation();

  /**
	 * Returns a new object of class '<em>Parameter</em>'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return a new object of class '<em>Parameter</em>'.
	 * @generated
	 */
  Parameter createParameter();

  /**
	 * Returns the package supported by this factory.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the package supported by this factory.
	 * @generated
	 */
  XModelPackage getXModelPackage();

} //XModelFactory
