/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.xmodel.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class XModelQuickfixProvider extends DefaultQuickfixProvider {
}
