/**
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.xmodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.xmodel.ui.AbstractXModelUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class XModelUiModule extends AbstractXModelUiModule {
  public XModelUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
