/*
 * generated by Xtext 2.18.0.M3
 */
package org.xtext.example.xmodel.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class XModelGrammarAccess extends AbstractGrammarElementFinder {
	
	public class PackageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.xmodel.XModel.Package");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPackageAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPackageKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cClassKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cClassAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cClassXClassParserRuleCall_4_2_0 = (RuleCall)cClassAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cClassAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cClassXClassParserRuleCall_4_3_1_0 = (RuleCall)cClassAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Package:
		//	{Package}
		//	'Package'
		//	name=EString
		//	'{' ('class' '{' class+=XClass ("," class+=XClass)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Package} 'Package' name=EString '{' ('class' '{' class+=XClass ("," class+=XClass)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Package}
		public Action getPackageAction_0() { return cPackageAction_0; }
		
		//'Package'
		public Keyword getPackageKeyword_1() { return cPackageKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('class' '{' class+=XClass ("," class+=XClass)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'class'
		public Keyword getClassKeyword_4_0() { return cClassKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//class+=XClass
		public Assignment getClassAssignment_4_2() { return cClassAssignment_4_2; }
		
		//XClass
		public RuleCall getClassXClassParserRuleCall_4_2_0() { return cClassXClassParserRuleCall_4_2_0; }
		
		//("," class+=XClass)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//class+=XClass
		public Assignment getClassAssignment_4_3_1() { return cClassAssignment_4_3_1; }
		
		//XClass
		public RuleCall getClassXClassParserRuleCall_4_3_1_0() { return cClassXClassParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class XClassElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.xmodel.XModel.XClass");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXClassAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cIsAbstractAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cIsAbstractIsAbstractKeyword_1_0 = (Keyword)cIsAbstractAssignment_1.eContents().get(0);
		private final Keyword cXClassKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDescriptionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDescriptionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_5_1_0 = (RuleCall)cDescriptionAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cExtendKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cExtendAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cExtendEStringParserRuleCall_6_1_0 = (RuleCall)cExtendAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cPropertyKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cPropertyAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cPropertyPropertyParserRuleCall_7_2_0 = (RuleCall)cPropertyAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cPropertyAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cPropertyPropertyParserRuleCall_7_3_1_0 = (RuleCall)cPropertyAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cOperationKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cOperationAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cOperationOperationParserRuleCall_8_2_0 = (RuleCall)cOperationAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cOperationAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cOperationOperationParserRuleCall_8_3_1_0 = (RuleCall)cOperationAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//XClass:
		//	{XClass} isAbstract?='isAbstract'?
		//	'XClass'
		//	name=EString
		//	'{' ('description' description=EString)? ('extend' extend=EString)? ('property' '{' property+=Property (","
		//	property+=Property)* '}')? ('operation' '{' operation+=Operation ("," operation+=Operation)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{XClass} isAbstract?='isAbstract'? 'XClass' name=EString '{' ('description' description=EString)? ('extend'
		//extend=EString)? ('property' '{' property+=Property ("," property+=Property)* '}')? ('operation' '{'
		//operation+=Operation ("," operation+=Operation)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{XClass}
		public Action getXClassAction_0() { return cXClassAction_0; }
		
		//isAbstract?='isAbstract'?
		public Assignment getIsAbstractAssignment_1() { return cIsAbstractAssignment_1; }
		
		//'isAbstract'
		public Keyword getIsAbstractIsAbstractKeyword_1_0() { return cIsAbstractIsAbstractKeyword_1_0; }
		
		//'XClass'
		public Keyword getXClassKeyword_2() { return cXClassKeyword_2; }
		
		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//('description' description=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'description'
		public Keyword getDescriptionKeyword_5_0() { return cDescriptionKeyword_5_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_5_1() { return cDescriptionAssignment_5_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_5_1_0() { return cDescriptionEStringParserRuleCall_5_1_0; }
		
		//('extend' extend=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'extend'
		public Keyword getExtendKeyword_6_0() { return cExtendKeyword_6_0; }
		
		//extend=EString
		public Assignment getExtendAssignment_6_1() { return cExtendAssignment_6_1; }
		
		//EString
		public RuleCall getExtendEStringParserRuleCall_6_1_0() { return cExtendEStringParserRuleCall_6_1_0; }
		
		//('property' '{' property+=Property ("," property+=Property)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'property'
		public Keyword getPropertyKeyword_7_0() { return cPropertyKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//property+=Property
		public Assignment getPropertyAssignment_7_2() { return cPropertyAssignment_7_2; }
		
		//Property
		public RuleCall getPropertyPropertyParserRuleCall_7_2_0() { return cPropertyPropertyParserRuleCall_7_2_0; }
		
		//("," property+=Property)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//property+=Property
		public Assignment getPropertyAssignment_7_3_1() { return cPropertyAssignment_7_3_1; }
		
		//Property
		public RuleCall getPropertyPropertyParserRuleCall_7_3_1_0() { return cPropertyPropertyParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//('operation' '{' operation+=Operation ("," operation+=Operation)* '}')?
		public Group getGroup_8() { return cGroup_8; }
		
		//'operation'
		public Keyword getOperationKeyword_8_0() { return cOperationKeyword_8_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }
		
		//operation+=Operation
		public Assignment getOperationAssignment_8_2() { return cOperationAssignment_8_2; }
		
		//Operation
		public RuleCall getOperationOperationParserRuleCall_8_2_0() { return cOperationOperationParserRuleCall_8_2_0; }
		
		//("," operation+=Operation)*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//operation+=Operation
		public Assignment getOperationAssignment_8_3_1() { return cOperationAssignment_8_3_1; }
		
		//Operation
		public RuleCall getOperationOperationParserRuleCall_8_3_1_0() { return cOperationOperationParserRuleCall_8_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.xmodel.XModel.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.xmodel.XModel.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class PropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.xmodel.XModel.Property");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPropertyAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPropertyKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cVisibilityKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cVisibilityAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cVisibilityVisibilityEnumRuleCall_5_1_0 = (RuleCall)cVisibilityAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cXtypeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cXtypeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cXtypeXTypeEnumRuleCall_6_1_0 = (RuleCall)cXtypeAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Property:
		//	{Property}
		//	'Property'
		//	name=EString
		//	'{' ('description' description=EString)? ('visibility' visibility=Visibility)? ('xtype' xtype=XType)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Property} 'Property' name=EString '{' ('description' description=EString)? ('visibility' visibility=Visibility)?
		//('xtype' xtype=XType)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Property}
		public Action getPropertyAction_0() { return cPropertyAction_0; }
		
		//'Property'
		public Keyword getPropertyKeyword_1() { return cPropertyKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('description' description=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }
		
		//('visibility' visibility=Visibility)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'visibility'
		public Keyword getVisibilityKeyword_5_0() { return cVisibilityKeyword_5_0; }
		
		//visibility=Visibility
		public Assignment getVisibilityAssignment_5_1() { return cVisibilityAssignment_5_1; }
		
		//Visibility
		public RuleCall getVisibilityVisibilityEnumRuleCall_5_1_0() { return cVisibilityVisibilityEnumRuleCall_5_1_0; }
		
		//('xtype' xtype=XType)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'xtype'
		public Keyword getXtypeKeyword_6_0() { return cXtypeKeyword_6_0; }
		
		//xtype=XType
		public Assignment getXtypeAssignment_6_1() { return cXtypeAssignment_6_1; }
		
		//XType
		public RuleCall getXtypeXTypeEnumRuleCall_6_1_0() { return cXtypeXTypeEnumRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class OperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.xmodel.XModel.Operation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOperationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOperationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cVisibilityKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cVisibilityAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cVisibilityVisibilityEnumRuleCall_5_1_0 = (RuleCall)cVisibilityAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cXtypeKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cXtypeAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cXtypeXTypeEnumRuleCall_6_1_0 = (RuleCall)cXtypeAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cParameterKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cParameterAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cParameterParameterParserRuleCall_7_2_0 = (RuleCall)cParameterAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cParameterAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cParameterParameterParserRuleCall_7_3_1_0 = (RuleCall)cParameterAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Operation:
		//	{Operation}
		//	'Operation'
		//	name=EString
		//	'{' ('description' description=EString)? ('visibility' visibility=Visibility)? ('xtype' xtype=XType)? ('parameter'
		//	'{' parameter+=Parameter ("," parameter+=Parameter)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Operation} 'Operation' name=EString '{' ('description' description=EString)? ('visibility' visibility=Visibility)?
		//('xtype' xtype=XType)? ('parameter' '{' parameter+=Parameter ("," parameter+=Parameter)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Operation}
		public Action getOperationAction_0() { return cOperationAction_0; }
		
		//'Operation'
		public Keyword getOperationKeyword_1() { return cOperationKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('description' description=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'description'
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }
		
		//('visibility' visibility=Visibility)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'visibility'
		public Keyword getVisibilityKeyword_5_0() { return cVisibilityKeyword_5_0; }
		
		//visibility=Visibility
		public Assignment getVisibilityAssignment_5_1() { return cVisibilityAssignment_5_1; }
		
		//Visibility
		public RuleCall getVisibilityVisibilityEnumRuleCall_5_1_0() { return cVisibilityVisibilityEnumRuleCall_5_1_0; }
		
		//('xtype' xtype=XType)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'xtype'
		public Keyword getXtypeKeyword_6_0() { return cXtypeKeyword_6_0; }
		
		//xtype=XType
		public Assignment getXtypeAssignment_6_1() { return cXtypeAssignment_6_1; }
		
		//XType
		public RuleCall getXtypeXTypeEnumRuleCall_6_1_0() { return cXtypeXTypeEnumRuleCall_6_1_0; }
		
		//('parameter' '{' parameter+=Parameter ("," parameter+=Parameter)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'parameter'
		public Keyword getParameterKeyword_7_0() { return cParameterKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//parameter+=Parameter
		public Assignment getParameterAssignment_7_2() { return cParameterAssignment_7_2; }
		
		//Parameter
		public RuleCall getParameterParameterParserRuleCall_7_2_0() { return cParameterParameterParserRuleCall_7_2_0; }
		
		//("," parameter+=Parameter)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//parameter+=Parameter
		public Assignment getParameterAssignment_7_3_1() { return cParameterAssignment_7_3_1; }
		
		//Parameter
		public RuleCall getParameterParameterParserRuleCall_7_3_1_0() { return cParameterParameterParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.xmodel.XModel.Parameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cParameterAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cParameterKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cXtypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cXtypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cXtypeXTypeEnumRuleCall_4_1_0 = (RuleCall)cXtypeAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Parameter:
		//	{Parameter}
		//	'Parameter'
		//	name=EString
		//	'{' ('xtype' xtype=XType)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Parameter} 'Parameter' name=EString '{' ('xtype' xtype=XType)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Parameter}
		public Action getParameterAction_0() { return cParameterAction_0; }
		
		//'Parameter'
		public Keyword getParameterKeyword_1() { return cParameterKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('xtype' xtype=XType)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'xtype'
		public Keyword getXtypeKeyword_4_0() { return cXtypeKeyword_4_0; }
		
		//xtype=XType
		public Assignment getXtypeAssignment_4_1() { return cXtypeAssignment_4_1; }
		
		//XType
		public RuleCall getXtypeXTypeEnumRuleCall_4_1_0() { return cXtypeXTypeEnumRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	public class VisibilityElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.xmodel.XModel.Visibility");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPublicEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPublicPublicKeyword_0_0 = (Keyword)cPublicEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cProtectedEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cProtectedProtectedKeyword_1_0 = (Keyword)cProtectedEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cPrivateEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cPrivatePrivateKeyword_2_0 = (Keyword)cPrivateEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Visibility:
		//	public | protected | private;
		public EnumRule getRule() { return rule; }
		
		//public | protected | private
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//public
		public EnumLiteralDeclaration getPublicEnumLiteralDeclaration_0() { return cPublicEnumLiteralDeclaration_0; }
		
		//'public'
		public Keyword getPublicPublicKeyword_0_0() { return cPublicPublicKeyword_0_0; }
		
		//protected
		public EnumLiteralDeclaration getProtectedEnumLiteralDeclaration_1() { return cProtectedEnumLiteralDeclaration_1; }
		
		//'protected'
		public Keyword getProtectedProtectedKeyword_1_0() { return cProtectedProtectedKeyword_1_0; }
		
		//private
		public EnumLiteralDeclaration getPrivateEnumLiteralDeclaration_2() { return cPrivateEnumLiteralDeclaration_2; }
		
		//'private'
		public Keyword getPrivatePrivateKeyword_2_0() { return cPrivatePrivateKeyword_2_0; }
	}
	public class XTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.xmodel.XModel.XType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cStringEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cStringStringKeyword_0_0 = (Keyword)cStringEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cIntegerEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cIntegerIntegerKeyword_1_0 = (Keyword)cIntegerEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cShortEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cShortShortKeyword_2_0 = (Keyword)cShortEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cByteEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cByteByteKeyword_3_0 = (Keyword)cByteEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cLongEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cLongLongKeyword_4_0 = (Keyword)cLongEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cFloatEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cFloatFloatKeyword_5_0 = (Keyword)cFloatEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cDoubleEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cDoubleDoubleKeyword_6_0 = (Keyword)cDoubleEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cCharacterEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cCharacterCharacterKeyword_7_0 = (Keyword)cCharacterEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cBooleanEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cBooleanBooleanKeyword_8_0 = (Keyword)cBooleanEnumLiteralDeclaration_8.eContents().get(0);
		
		//enum XType:
		//	String | Integer | Short | Byte | Long | Float | Double | Character | Boolean;
		public EnumRule getRule() { return rule; }
		
		//String | Integer | Short | Byte | Long | Float | Double | Character | Boolean
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//String
		public EnumLiteralDeclaration getStringEnumLiteralDeclaration_0() { return cStringEnumLiteralDeclaration_0; }
		
		//'String'
		public Keyword getStringStringKeyword_0_0() { return cStringStringKeyword_0_0; }
		
		//Integer
		public EnumLiteralDeclaration getIntegerEnumLiteralDeclaration_1() { return cIntegerEnumLiteralDeclaration_1; }
		
		//'Integer'
		public Keyword getIntegerIntegerKeyword_1_0() { return cIntegerIntegerKeyword_1_0; }
		
		//Short
		public EnumLiteralDeclaration getShortEnumLiteralDeclaration_2() { return cShortEnumLiteralDeclaration_2; }
		
		//'Short'
		public Keyword getShortShortKeyword_2_0() { return cShortShortKeyword_2_0; }
		
		//Byte
		public EnumLiteralDeclaration getByteEnumLiteralDeclaration_3() { return cByteEnumLiteralDeclaration_3; }
		
		//'Byte'
		public Keyword getByteByteKeyword_3_0() { return cByteByteKeyword_3_0; }
		
		//Long
		public EnumLiteralDeclaration getLongEnumLiteralDeclaration_4() { return cLongEnumLiteralDeclaration_4; }
		
		//'Long'
		public Keyword getLongLongKeyword_4_0() { return cLongLongKeyword_4_0; }
		
		//Float
		public EnumLiteralDeclaration getFloatEnumLiteralDeclaration_5() { return cFloatEnumLiteralDeclaration_5; }
		
		//'Float'
		public Keyword getFloatFloatKeyword_5_0() { return cFloatFloatKeyword_5_0; }
		
		//Double
		public EnumLiteralDeclaration getDoubleEnumLiteralDeclaration_6() { return cDoubleEnumLiteralDeclaration_6; }
		
		//'Double'
		public Keyword getDoubleDoubleKeyword_6_0() { return cDoubleDoubleKeyword_6_0; }
		
		//Character
		public EnumLiteralDeclaration getCharacterEnumLiteralDeclaration_7() { return cCharacterEnumLiteralDeclaration_7; }
		
		//'Character'
		public Keyword getCharacterCharacterKeyword_7_0() { return cCharacterCharacterKeyword_7_0; }
		
		//Boolean
		public EnumLiteralDeclaration getBooleanEnumLiteralDeclaration_8() { return cBooleanEnumLiteralDeclaration_8; }
		
		//'Boolean'
		public Keyword getBooleanBooleanKeyword_8_0() { return cBooleanBooleanKeyword_8_0; }
	}
	
	private final PackageElements pPackage;
	private final XClassElements pXClass;
	private final EStringElements pEString;
	private final EBooleanElements pEBoolean;
	private final PropertyElements pProperty;
	private final OperationElements pOperation;
	private final VisibilityElements eVisibility;
	private final XTypeElements eXType;
	private final ParameterElements pParameter;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public XModelGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pPackage = new PackageElements();
		this.pXClass = new XClassElements();
		this.pEString = new EStringElements();
		this.pEBoolean = new EBooleanElements();
		this.pProperty = new PropertyElements();
		this.pOperation = new OperationElements();
		this.eVisibility = new VisibilityElements();
		this.eXType = new XTypeElements();
		this.pParameter = new ParameterElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.xmodel.XModel".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Package:
	//	{Package}
	//	'Package'
	//	name=EString
	//	'{' ('class' '{' class+=XClass ("," class+=XClass)* '}')?
	//	'}';
	public PackageElements getPackageAccess() {
		return pPackage;
	}
	
	public ParserRule getPackageRule() {
		return getPackageAccess().getRule();
	}
	
	//XClass:
	//	{XClass} isAbstract?='isAbstract'?
	//	'XClass'
	//	name=EString
	//	'{' ('description' description=EString)? ('extend' extend=EString)? ('property' '{' property+=Property (","
	//	property+=Property)* '}')? ('operation' '{' operation+=Operation ("," operation+=Operation)* '}')?
	//	'}';
	public XClassElements getXClassAccess() {
		return pXClass;
	}
	
	public ParserRule getXClassRule() {
		return getXClassAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//Property:
	//	{Property}
	//	'Property'
	//	name=EString
	//	'{' ('description' description=EString)? ('visibility' visibility=Visibility)? ('xtype' xtype=XType)?
	//	'}';
	public PropertyElements getPropertyAccess() {
		return pProperty;
	}
	
	public ParserRule getPropertyRule() {
		return getPropertyAccess().getRule();
	}
	
	//Operation:
	//	{Operation}
	//	'Operation'
	//	name=EString
	//	'{' ('description' description=EString)? ('visibility' visibility=Visibility)? ('xtype' xtype=XType)? ('parameter'
	//	'{' parameter+=Parameter ("," parameter+=Parameter)* '}')?
	//	'}';
	public OperationElements getOperationAccess() {
		return pOperation;
	}
	
	public ParserRule getOperationRule() {
		return getOperationAccess().getRule();
	}
	
	//enum Visibility:
	//	public | protected | private;
	public VisibilityElements getVisibilityAccess() {
		return eVisibility;
	}
	
	public EnumRule getVisibilityRule() {
		return getVisibilityAccess().getRule();
	}
	
	//enum XType:
	//	String | Integer | Short | Byte | Long | Float | Double | Character | Boolean;
	public XTypeElements getXTypeAccess() {
		return eXType;
	}
	
	public EnumRule getXTypeRule() {
		return getXTypeAccess().getRule();
	}
	
	//Parameter:
	//	{Parameter}
	//	'Parameter'
	//	name=EString
	//	'{' ('xtype' xtype=XType)?
	//	'}';
	public ParameterElements getParameterAccess() {
		return pParameter;
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
